### ISSUE TITLE
Tools used

### ISSUE THREAD

**Issue by maciekish** [BlueFinBima/DCS-Fonts#2]
Hi, how did you extract these? I need the fonts for the A-10C.

**Comment by BlueFinBima** [comment]
Hi @maciekish , I used FontForge to create the fonts from scratch based on the images of the fonts in DCS.  You might find the font you're looking for here https://github.com/BlueFinBima/DCS-Fonts/tree/master/Hornet%20Harrier%20Hawg%20Fonts/Source

**Comment by BlueFinBima** [comment]
@maciekish I've enabled discussions on the repo in case you want to discuss further.
